(ns qcjs)

(def Config (. js/qc -Config))
(def ConsoleListener (. js/qc -ConsoleListener))
(def Distribution (. js/qc -Distribution))
(def HtmlListener (. js/qc -HtmlListener))
(def NodeConsoleListener (. js/qc -NodeConsoleListener))
(def Prop (. js/qc -Prop))
(def allProps (. js/qc -allProps))
(def choose (. js/qc -choose))
(def expectException (. js/qc -expectException))
(def failOnException (. js/qc -failOnException))
(def frequency (. js/qc -frequency))
(def generateShrunkValues (. js/qc -generateShrunkValues))
(def generateValue (. js/qc -generateValue))
(def generator (. js/qc -generator))
(def getFloat (. js/qc -getFloat))
(def getInteger (. js/qc -getInteger))
(def getPositiveInteger (. js/qc -getPositiveInteger))
(def justSize (. js/qc -justSize))
(def resetProps (. js/qc -resetProps))
(def runProps (. js/qc -runProps))
(def shrinkLoop (. js/qc -shrinkLoop))

(defn qcheck [title gens f]
  (.declare js/qc title (. gens -array) f))
